const BASE_URL = 'http://localhost:3001/api';
const PROJECT_MANAGER = 'PROJECT_MANAGER';
const DEVELOPER = 'DEVELOPER';
const DESIGNER = 'DESIGNER';
const TESTER = 'TESTER';
const SECURITY = 'SECURITY';
export { BASE_URL, PROJECT_MANAGER, DESIGNER, DEVELOPER, SECURITY, TESTER }

